import {
  LANGUAGE_LABELS,
  SUPPORTED_LANGUAGES,
} from '../../services/language-config';
import { Language } from '../../services/translation.service';

type RentalLangOption = { code: Language; label: string };

type ExtendedRentalLanguage = 'es' | 'it' | 'ar' | 'ru';

const BOOKING_LANGUAGE_OPTIONS: RentalLangOption[] = SUPPORTED_LANGUAGES.map(
  (code) => ({ code, label: LANGUAGE_LABELS[code] }),
);

export const EXTENDED_RENTAL_PAGE_COPY: Record<ExtendedRentalLanguage, any> = {
  es: {
    serviceHighlightsAria: 'Aspectos destacados del servicio',
    heroChip: 'Alquiler de Bicicletas Freiburg',
    heroAccent: 'a partir de 8 €',
    heroDescription:
      'Los días 1 a 7 se calculan individualmente para cada bicicleta, a partir del día 8 se aplica un complemento fijo. Retiro directo en nuestro establecimiento en Freiburg.',
    heroFeatures: [
      'Candado incluido',
      'Casco gratis',
      'Disponible inmediatamente',
      'Depósito de 300 EUR (efectivo)',
    ],
    heroPriceCard: {
      badge: 'Lógica de precios personalizada',
      duration: '1-7 días',
      price: 'configurado por bicicleta',
      perDay: 'administrado manualmente en admin',
      vs: 'a partir del día 8 con complemento fijo',
      features: ['✔ Candado', '✔ Casco', '✔ Inmediato'],
    },
    signatureLabel: 'Sistema de Alquiler Urbano',
    signatureText:
      'Diseñado como un estudio de rendimiento moderno: reserva rápida, precios claros y retiro sin fricciones.',
    signatureStats: [
      { value: '1-7 días', label: 'personalizado por bicicleta' },
      { value: 'Casco + Candado', label: 'Siempre incluido' },
    ],
    pricingCards: [
      {
        className: 'pcard-popular',
        topBadge: '🔥 Popular',
        label: 'Flexible',
        duration: '1 a 7 días',
        price: 'Precios diarios personalizados',
        perDay: 'configurados separadamente por bicicleta',
        features: [
          'Candado incluido',
          'Casco incluido',
          'Disponible inmediatamente',
        ],
        cta: 'Elige una bicicleta y reserva ahora',
        whatsapp: 'WhatsApp',
      },
      {
        className: 'pcard-best',
        topBadge: 'Extensión personalizada',
        topBadgeClass: 'pcard-best-badge',
        label: 'A partir del día 8',
        duration: 'Base 7 días + complemento',
        price: 'configurado por bicicleta',
        perDay: 'cada día extra agrega un complemento fijo',
        features: [
          'Candado incluido',
          'Casco incluido',
          'Disponible inmediatamente',
        ],
        cta: 'Elige una bicicleta y reserva ahora',
        whatsapp: 'WhatsApp',
      },
      {
        className: '',
        label: 'Extensión',
        duration: 'a partir del día 8',
        price: 'Precio 7 días + complemento',
        perDay: 'complemento fijo por cada día extra',
        features: [
          'Candado incluido',
          'Casco incluido',
          'Disponible inmediatamente',
        ],
        cta: 'Elige una bicicleta y reserva ahora',
        whatsapp: 'WhatsApp',
      },
    ],
    pricingExtras: [
      {
        duration: 'Días 1-3',
        price: 'Mostrado directamente en la bicicleta',
        day: 'Sin tarifas fijas ocultas',
        cta: 'Reservar',
      },
      {
        duration: 'Días 4-7',
        price: 'También configurable separadamente',
        day: 'Ideal para alquiler semanal',
        cta: 'Reservar',
      },
      {
        duration: 'A partir del día 8',
        price: 'Precio 7 días + complemento',
        day: 'Por día adicional',
        cta: 'Reservar',
      },
    ],
    pricingInfo: [
      { title: 'Depósito', text: '300 EUR en efectivo, reembolsado al retiro' },
      {
        title: 'Incluido',
        text: 'Candado y casco incluidos sin cargo adicional',
      },
      {
        title: 'Horario de apertura',
        text: 'Lun, Mar, Jue 11-17:30 · Mié 14-17:30 · Vie 11-13 y 15-18 · Sab 11:30-17',
      },
    ],
    bikePriceFrom: 'desde',
    extraDayShort: '+1d',
    zoomImageAriaLabel: 'Ampliar imagen',
    lightboxAriaLabel: 'Imagen ampliada',
    lightboxCloseAriaLabel: 'Cerrar',
    lightboxPrevAriaLabel: 'Imagen anterior',
    lightboxNextAriaLabel: 'Próxima imagen',
    reviewStarAriaSuffix: 'estrellas',
    bikeFactLabels: {
      type: 'Tipo',
      category: 'Categoría',
      frame: 'Marco',
      tire: 'Llanta',
      color: 'Color',
    },
    extraDayPriceLabel: 'A partir del día 8 por día extra',
    successEmailPrefix: 'Una confirmación fue enviada a',
    successEmailSuffix: '.',
    weekdays: ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sab', 'Dom'],
    emailLabel: 'Correo Electrónico',
    placeholders: {
      firstName: 'Juan',
      lastName: 'García',
      email: 'juan@example.com',
      phone: '+49 ...',
      notes: 'Solicitudes especiales, preguntas...',
    },
    bookingLanguages: BOOKING_LANGUAGE_OPTIONS,
    whatsappTitle: 'WhatsApp',
    bookingErrors: {
      busyRange:
        'Este período ya contiene días reservados. Por favor elige otro período.',
      choosePeriod: 'Por favor elige un período de alquiler.',
      invalidEnd: 'La fecha de fin no puede ser anterior a la fecha de inicio.',
      fullName: 'Por favor ingresa tu nombre completo.',
      validEmail: 'Por favor ingresa una dirección de correo válida.',
      generic: 'Ocurrió un error. Por favor intenta de nuevo.',
    },
    addBikeLabel: 'Agregar bicicleta',
    priceSummaryLabel: 'Resumen de precios',
    totalRentalLabel: 'Alquiler total',
    totalKautionLabel: 'Depósito total',
    kautionInfoNotice:
      'Atención: se requiere un depósito por cada bicicleta. Tráigalo en efectivo el día de recogida — le será devuelto íntegramente al devolverla.',
    kautionSuccessReminder:
      'Por favor, traiga el depósito en efectivo el día de recogida.',
  },
  it: {
    serviceHighlightsAria: 'Punti forti del servizio',
    heroChip: 'Noleggio bici Friburgo',
    heroAccent: 'a partire da 8 €',
    heroDescription:
      'I giorni 1-7 sono calcolati individualmente per ogni bici, dal giorno 8 in poi si applica un supplemento fisso al giorno. Ritira direttamente presso il nostro negozio a Friburgo.',
    heroFeatures: [
      'Lucchetto incluso',
      'Casco gratuito',
      'Disponibile subito',
      'Deposito 300 EUR (contanti)',
    ],
    heroPriceCard: {
      badge: 'Logica di prezzo personalizzata',
      duration: '1-7 giorni',
      price: 'configurato per bici',
      perDay: 'gestito manualmente in admin',
      vs: 'dal giorno 8 con supplemento fisso',
      features: ['✔ Lucchetto', '✔ Casco', '✔ Immediato'],
    },
    signatureLabel: 'Sistema di noleggio urbano',
    signatureText:
      'Progettato come uno studio di performance moderno: prenotazione veloce, prezzi chiari e ritiro senza attriti.',
    signatureStats: [
      { value: '1-7 giorni', label: 'personalizzato per bici' },
      { value: 'Casco + lucchetto', label: 'Sempre incluso' },
    ],
    pricingCards: [
      {
        className: 'pcard-popular',
        topBadge: '🔥 Popolare',
        label: 'Flessibile',
        duration: '1 a 7 giorni',
        price: 'Prezzi giornalieri personalizzati',
        perDay: 'configurati separatamente per bici',
        features: ['Lucchetto incluso', 'Casco incluso', 'Disponibile subito'],
        cta: 'Scegli bici e prenota subito',
        whatsapp: 'WhatsApp',
      },
      {
        className: 'pcard-best',
        topBadge: 'Estensione personalizzata',
        topBadgeClass: 'pcard-best-badge',
        label: 'Dal giorno 8',
        duration: 'Base 7 giorni + supplemento',
        price: 'configurato per bici',
        perDay: 'ogni giorno extra aggiunge un supplemento fisso',
        features: ['Lucchetto incluso', 'Casco incluso', 'Disponibile subito'],
        cta: 'Scegli bici e prenota subito',
        whatsapp: 'WhatsApp',
      },
      {
        className: '',
        label: 'Estensione',
        duration: 'dal giorno 8',
        price: 'Prezzo 7 giorni + supplemento',
        perDay: 'supplemento fisso per ogni giorno extra',
        features: ['Lucchetto incluso', 'Casco incluso', 'Disponibile subito'],
        cta: 'Scegli bici e prenota subito',
        whatsapp: 'WhatsApp',
      },
    ],
    pricingExtras: [
      {
        duration: 'Giorni 1-3',
        price: 'visibile direttamente sulla bici',
        day: 'niente costi nascosti',
        cta: 'Prenota',
      },
      {
        duration: 'Giorni 4-7',
        price: 'anche configurabile separatamente',
        day: 'ideale per il noleggio settimanale',
        cta: 'Prenota',
      },
      {
        duration: 'Dal giorno 8',
        price: 'Prezzo 7 giorni + supplemento',
        day: 'per giorno aggiuntivo',
        cta: 'Prenota',
      },
    ],
    pricingInfo: [
      { title: 'Deposito', text: '300 EUR contanti, rimborsato al ritiro' },
      {
        title: 'Sempre incluso',
        text: 'Lucchetto e casco inclusi senza costi aggiuntivi',
      },
      {
        title: 'Orari di apertura',
        text: 'Lun, Mar, Gio 11-17:30 · Mer 14-17:30 · Ven 11-13 & 15-18 · Sab 11:30-17',
      },
    ],
    bikePriceFrom: 'da',
    extraDayShort: '+1G',
    zoomImageAriaLabel: 'Ingrandisci immagine',
    lightboxAriaLabel: 'Immagine ingrandita',
    lightboxCloseAriaLabel: 'Chiudi',
    lightboxPrevAriaLabel: 'Immagine precedente',
    lightboxNextAriaLabel: 'Immagine successiva',
    reviewStarAriaSuffix: 'stelle',
    bikeFactLabels: {
      type: 'Tipo',
      category: 'Categoria',
      frame: 'Telaio',
      tire: 'Pneumatico',
      color: 'Colore',
    },
    extraDayPriceLabel: 'Dal giorno 8 per giorno extra',
    successEmailPrefix: 'Una conferma è stata inviata a',
    successEmailSuffix: '.',
    weekdays: ['Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Dom'],
    emailLabel: 'Email',
    placeholders: {
      firstName: 'Marco',
      lastName: 'Rossi',
      email: 'marco@example.com',
      phone: '+39 ...',
      notes: 'Richieste speciali, domande...',
    },
    bookingLanguages: BOOKING_LANGUAGE_OPTIONS,
    whatsappTitle: 'WhatsApp',
    bookingErrors: {
      busyRange:
        'Questo periodo contiene già giorni prenotati. Seleziona un altro periodo.',
      choosePeriod: 'Seleziona un periodo di noleggio.',
      invalidEnd: 'La data di fine non può essere prima della data di inizio.',
      fullName: 'Inserisci il tuo nome completo.',
      validEmail: 'Inserisci un indirizzo email valido.',
      generic: 'Si è verificato un errore. Riprova.',
    },
    addBikeLabel: 'Aggiungi bici',
    priceSummaryLabel: 'Riepilogo prezzi',
    totalRentalLabel: 'Noleggio totale',
    totalKautionLabel: 'Deposito totale',
    kautionInfoNotice:
      'Attenzione: per ogni bici è richiesta una cauzione. Portarla in contanti il giorno del ritiro — verrà restituita integralmente alla riconsegna.',
    kautionSuccessReminder:
      'Si prega di portare la cauzione in contanti il giorno del ritiro.',
  },
  ar: {
    serviceHighlightsAria: 'نقاط قوة الخدمة',
    heroChip: 'استئجار الدراجات فرايبورج',
    heroAccent: 'ابتداءً من 8 €',
    heroDescription:
      'يتم حساب الأيام من 1 إلى 7 بشكل فردي لكل دراجة، ثم يتم تطبيق رسم إضافي ثابت من اليوم 8. الاستلام المباشر من متجرنا في فرايبورج.',
    heroFeatures: [
      'القفل مدرج',
      'الخوذة مجانية',
      'متاح فورًا',
      'إيداع 300 يورو (نقدًا)',
    ],
    heroPriceCard: {
      badge: 'منطق التسعير الفردي',
      duration: '1-7 أيام',
      price: 'منفصل لكل دراجة',
      perDay: 'يتم إدخاله يدويًا في لوحة التحكم',
      vs: 'من اليوم 8 مع رسم إضافي ثابت',
      features: ['✔ القفل', '✔ الخوذة', '✔ جاهز'],
    },
    signatureLabel: 'نظام الإيجار الحضري',
    signatureText:
      'مصمم مثل استوديو الأداء الحديث: الحجز السريع والأسعار الواضحة والاستلام بدون عناء.',
    signatureStats: [
      { value: '1-7 أيام', label: 'فردي لكل دراجة' },
      { value: 'الخوذة + القفل', label: 'دائمًا مدرجة' },
    ],
    pricingCards: [
      {
        className: 'pcard-popular',
        topBadge: '🔥 شهير',
        label: 'مرن',
        duration: '1 إلى 7 أيام',
        price: 'أسعار يومية فردية',
        perDay: 'تم تكوينها بشكل منفصل لكل دراجة',
        features: ['القفل مدرج', 'الخوذة مدرجة', 'متاح فورًا'],
        cta: 'اختر دراجة واحجزها الآن',
        whatsapp: 'WhatsApp',
      },
      {
        className: 'pcard-best',
        topBadge: 'تمديد فردي',
        topBadgeClass: 'pcard-best-badge',
        label: 'من اليوم 8',
        duration: 'أساس 7 أيام + رسم إضافي',
        price: 'تم تكوينه لكل دراجة',
        perDay: 'يضيف كل يوم إضافي رسم إضافي ثابت',
        features: ['القفل مدرج', 'الخوذة مدرجة', 'متاح فورًا'],
        cta: 'اختر دراجة واحجزها الآن',
        whatsapp: 'WhatsApp',
      },
      {
        className: '',
        label: 'تمديد',
        duration: 'من اليوم 8',
        price: 'سعر 7 أيام + الإضافية',
        perDay: 'رسم إضافي ثابت لكل يوم إضافي',
        features: ['القفل مدرج', 'الخوذة مدرجة', 'متاح فورًا'],
        cta: 'اختر دراجة واحجزها الآن',
        whatsapp: 'WhatsApp',
      },
    ],
    pricingExtras: [
      {
        duration: 'الأيام 1-3',
        price: 'مرئي مباشرة على الدراجة',
        day: 'بدون رسوم مخفية',
        cta: 'احجز',
      },
      {
        duration: 'الأيام 4-7',
        price: 'قابل للتكوين أيضًا بشكل منفصل',
        day: 'مثالي لاستئجار أسبوعي',
        cta: 'احجز',
      },
      {
        duration: 'من اليوم 8',
        price: 'سعر 7 أيام + رسم إضافي',
        day: 'لكل يوم إضافي',
        cta: 'احجز',
      },
    ],
    pricingInfo: [
      { title: 'الإيداع', text: '300 يورو نقدًا، يتم رده عند الإرجاع' },
      {
        title: 'مدرج دائمًا',
        text: 'القفل والخوذة مدرج بدون رسم إضافي',
      },
      {
        title: 'ساعات العمل',
        text: 'الاثنين والثلاثاء والخميس 11-17:30 · الأربعاء 14-17:30 · الجمعة 11-13 & 15-18 · السبت 11:30-17',
      },
    ],
    bikePriceFrom: 'من',
    extraDayShort: '+1د',
    zoomImageAriaLabel: 'تكبير الصورة',
    lightboxAriaLabel: 'صورة مكبرة',
    lightboxCloseAriaLabel: 'إغلاق',
    lightboxPrevAriaLabel: 'الصورة السابقة',
    lightboxNextAriaLabel: 'الصورة التالية',
    reviewStarAriaSuffix: 'نجوم',
    bikeFactLabels: {
      type: 'النوع',
      category: 'الفئة',
      frame: 'الإطار',
      tire: 'الإطار',
      color: 'اللون',
    },
    extraDayPriceLabel: 'من اليوم 8 لكل يوم إضافي',
    successEmailPrefix: 'تم إرسال تأكيد إلى',
    successEmailSuffix: '.',
    weekdays: [
      'الاثنين',
      'الثلاثاء',
      'الأربعاء',
      'الخميس',
      'الجمعة',
      'السبت',
      'الأحد',
    ],
    emailLabel: 'البريد الإلكتروني',
    placeholders: {
      firstName: 'محمد',
      lastName: 'علي',
      email: 'max@example.com',
      phone: '+49 ...',
      notes: 'طلبات خاصة وأسئلة...',
    },
    bookingLanguages: BOOKING_LANGUAGE_OPTIONS,
    whatsappTitle: 'WhatsApp',
    bookingErrors: {
      busyRange:
        'تحتوي هذه الفترة بالفعل على أيام محجوزة. يرجى اختيار فترة أخرى.',
      choosePeriod: 'يرجى اختيار فترة إيجار.',
      invalidEnd: 'لا يمكن أن يكون تاريخ الانتهاء قبل تاريخ البداية.',
      fullName: 'يرجى إدخال اسمك الكامل.',
      validEmail: 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
      generic: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    },
    addBikeLabel: 'إضافة دراجة',
    priceSummaryLabel: 'ملخص الأسعار',
    totalRentalLabel: 'إجمالي الإيجار',
    totalKautionLabel: 'إجمالي الوديعة',
    kautionInfoNotice:
      'تنبيه: يُطلب وديعة لكل دراجة. يُرجى إحضارها نقداً يوم الاستلام — وسيتم ردّها كاملاً عند الإعادة.',
    kautionSuccessReminder: 'يُرجى إحضار الوديعة نقداً يوم الاستلام.',
  },
  ru: {
    serviceHighlightsAria: 'Основные достоинства услуги',
    heroChip: 'Аренда велосипедов Фрайбург',
    heroAccent: 'от 8 €',
    heroDescription:
      'Дни 1-7 рассчитываются индивидуально для каждого велосипеда, с 8-го дня применяется фиксированная доплата. Самовывоз прямо в нашем магазине во Фрайбурге.',
    heroFeatures: [
      'Замок включен',
      'Шлем бесплатно',
      'Доступно сразу',
      '300 EUR залог (наличные)',
    ],
    heroPriceCard: {
      badge: 'Индивидуальная логика ценообразования',
      duration: '1-7 дней',
      price: 'за каждый велосипед отдельно',
      perDay: 'настраивается вручную в админке',
      vs: 'с 8-го дня фиксированная доплата',
      features: ['✔ Замок', '✔ Шлем', '✔ Готово'],
    },
    signatureLabel: 'Система аренды в городе',
    signatureText:
      'Разработана как современная студия производительности: быстрое бронирование, прозрачные цены и беспроблемный самовывоз.',
    signatureStats: [
      { value: '1-7 дней', label: 'индивидуально за велосипед' },
      { value: 'Шлем + замок', label: 'Всегда включено' },
    ],
    pricingCards: [
      {
        className: 'pcard-popular',
        topBadge: '🔥 Популярно',
        label: 'Гибко',
        duration: '1-7 дней',
        price: 'Индивидуальные дневные цены',
        perDay: 'настраивается отдельно за каждый велосипед',
        features: ['Замок включен', 'Шлем включен', 'Доступно сразу'],
        cta: 'Выбрать велосипед и зарезервировать',
        whatsapp: 'WhatsApp',
      },
      {
        className: 'pcard-best',
        topBadge: 'Индивидуальное продление',
        topBadgeClass: 'pcard-best-badge',
        label: 'С 8-го дня',
        duration: '7-дневная база + доплата',
        price: 'настраивается за велосипед',
        perDay: 'каждый дополнительный день добавляет фиксированную доплату',
        features: ['Замок включен', 'Шлем включен', 'Доступно сразу'],
        cta: 'Выбрать велосипед и зарезервировать',
        whatsapp: 'WhatsApp',
      },
      {
        className: '',
        label: 'Продление',
        duration: 'с 8-го дня',
        price: '7-дневная цена + дополнение',
        perDay: 'фиксированная доплата за каждый дополнительный день',
        features: ['Замок включен', 'Шлем включен', 'Доступно сразу'],
        cta: 'Выбрать велосипед и зарезервировать',
        whatsapp: 'WhatsApp',
      },
    ],
    pricingExtras: [
      {
        duration: 'Дни 1-3',
        price: 'отображаются прямо на велосипеде',
        day: 'без скрытых сборов',
        cta: 'Зарезервировать',
      },
      {
        duration: 'Дни 4-7',
        price: 'также отдельно настраиваемые',
        day: 'идеально для недельной аренды',
        cta: 'Зарезервировать',
      },
      {
        duration: 'С 8-го дня',
        price: '7-дневная цена + доплата',
        day: 'за дополнительный день',
        cta: 'Зарезервировать',
      },
    ],
    pricingInfo: [
      { title: 'Залог', text: '300 EUR наличными, возвращается при возврате' },
      {
        title: 'Всегда включено',
        text: 'Замок и шлем включены без дополнительной платы',
      },
      {
        title: 'Часы работы',
        text: 'Пн, Вт, Чт 11-17:30 · Ср 14-17:30 · Пт 11-13 и 15-18 · Сб 11:30-17',
      },
    ],
    bikePriceFrom: 'от',
    extraDayShort: '+1д',
    zoomImageAriaLabel: 'Увеличить изображение',
    lightboxAriaLabel: 'Увеличенное изображение',
    lightboxCloseAriaLabel: 'Закрыть',
    lightboxPrevAriaLabel: 'Предыдущее изображение',
    lightboxNextAriaLabel: 'Следующее изображение',
    reviewStarAriaSuffix: 'звезд',
    bikeFactLabels: {
      type: 'Тип',
      category: 'Категория',
      frame: 'Рама',
      tire: 'Шина',
      color: 'Цвет',
    },
    extraDayPriceLabel: 'С 8-го дня за каждый дополнительный день',
    successEmailPrefix: 'Подтверждение было отправлено на',
    successEmailSuffix: '.',
    weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
    emailLabel: 'Электронная почта',
    placeholders: {
      firstName: 'Иван',
      lastName: 'Иванов',
      email: 'ivan@example.com',
      phone: '+49 ...',
      notes: 'Особые пожелания, вопросы...',
    },
    bookingLanguages: BOOKING_LANGUAGE_OPTIONS,
    whatsappTitle: 'WhatsApp',
    bookingErrors: {
      busyRange:
        'Этот период уже содержит забронированные дни. Пожалуйста, выберите другой период.',
      choosePeriod: 'Пожалуйста, выберите период аренды.',
      invalidEnd: 'Дата окончания не может быть раньше даты начала.',
      fullName: 'Пожалуйста, введите ваше полное имя.',
      validEmail: 'Пожалуйста, введите действительный адрес электронной почты.',
      generic: 'Произошла ошибка. Пожалуйста, попробуйте еще раз.',
    },
    addBikeLabel: 'Добавить велосипед',
    priceSummaryLabel: 'Обзор цен',
    totalRentalLabel: 'Итого аренда',
    totalKautionLabel: 'Итого залог',
    kautionInfoNotice:
      'Обратите внимание: для каждого велосипеда требуется залог. Пожалуйста, принесите его наличными в день получения — он будет полностью возвращён при сдаче.',
    kautionSuccessReminder:
      'Пожалуйста, принесите залог наличными в день получения.',
  },
};
